AWSTemplateFormatVersion: 2010-09-09
Description: Create EC2 instance associate with security group
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      SecurityGroups:
         - !Ref InstanceSecurityGroup
      KeyName: udacityKeyPair
      ImageId: 'ami-053b0d53c279acc90'
      InstanceType: t3.micro

  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
         - IpProtocol: tcp
           FromPort: '22'
           ToPort: '22'
           CidrIp: 0.0.0.0/0 