version: 2.1
jobs:
  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Run hello
          command: |
            echo "Hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Run World
          command: |
            echo " World!"

workflows:
  default:
    jobs:
      - print_hello
      - print_world:
          requires:
            - print_hello
