version: 2.1
jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Run save file
          command: |
            echo "My text to output here" > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            - output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Run read sharing files
          command: |
            echo " World!"
      - attach_workspace:
          at: /tmp/workspace
workflows:
  default:
    jobs:
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
