version: 2.1
commands:
  print_pipeline_id:
    parameters:
      id:
        type: string
        default: "Default"
    steps:
    - run: echo << parameters.id >>
jobs:
  print_hello:
    docker:
    - image: circleci/node:13.8.0
    steps:
    - print_pipeline_id:
        id: $CIRCLE_WORKFLOW_ID

workflows:
  print_workflow:
    jobs:
    - print_hello
