version: 2.1
jobs:
  configure_infrastructure:
    docker:
      - image: python:3.9.16-alpine
    steps:

      - add_ssh_keys:
          fingerprints:
            - "a6:4a:f9:0d:5d:7e:16:84:80:a5:95:cc:09:e1:0a:11"
      - checkout
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Check Ansible
          command: |
            ansible --version
      - run:
          name: Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml

workflows:
  my_workflow:
    jobs:
      - configure_infrastructure
